// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CommonController from "./common_controller";
application.register("common", CommonController);

import HomesController from "./homes_controller";
application.register("homes", HomesController);
